server:
  port: 8089
  servlet:
    contextPath: /api-gateway


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: patient-details
          uri: lb://patient-details
          predicates:
            - Path=/patients/**

management:
  tracing:
    sampling:
      probability: 1.0